"""Add team_id to Project

Revision ID: 80a904f5c532
Revises: 6224db2a63a5
Create Date: 2025-07-21 06:15:47.619773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a904f5c532'
down_revision = '6224db2a63a5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            constraint_name='fk_project_team_id',
            referent_table='team',
            local_cols=['team_id'],
            remote_cols=['id']
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
